### ISSUE TITLE
Vanth/Orcus data incorrect, and Quaoar listed as having no moons.

### ISSUE THREAD

**Issue by Jollus174** [systeme-solaire/api-rest#10]
Orcus looks like it should have a single moon named 'Vanth' (the data for this exists in the API).
Likewise, Quaoar should also have its single moon 'Weywot' linked in the data.

**Comment by khrys63** [comment]
Hi
I dont understand your problem.
Orcus, Vanth, Quaoar and Weywaot are present in the API.

https://api.le-systeme-solaire.net/rest/bodies/orcus
https://api.le-systeme-solaire.net/rest/bodies/vanth
https://api.le-systeme-solaire.net/rest/bodies/quaoar
https://api.le-systeme-solaire.net/rest/bodies/weywot

**Comment by Jollus174** [comment]
@khrys63 
Oh, interesting... they seem to be working in those links.
If the unfiltered API data is requested (via https://api.le-systeme-solaire.net/rest/bodies), then all Dwarf Planets with moons (Pluto, Eris, Makemake, Haumea, Orcus, Quoaor) seem to have their 'moons' key set to 'null'.

![image](https://user-images.githubusercontent.com/30223207/148627994-a1939414-5552-4d8c-b974-60a6c16b6d51.png)

Looking up the moons individually from the data dump lists their 'aroundPlanet' key correctly, but it's the Dwarf Planets themselves that seem to lack the proper reference.

**Comment by khrys63** [comment]
You re right.
I will inspect that.

**Comment by khrys63** [comment]
I fix it.

It's OK for planets, dwarf planets and asteroids.

Thanks for feedback.
