### ISSUE TITLE
S/2003 J 24 missing from the Jupiter moon data.

### ISSUE THREAD

**Issue by Jollus174** [systeme-solaire/api-rest#11]
It's one of the many moons, but while parsing them for my own personal project I noticed this one is missing.
https://en.wikipedia.org/wiki/S/2003_J_24

The API seems to return no record of this particular entity.

Were there any contribution instructions? I'd love to be able to contribute some updates for this.

**Comment by khrys63** [comment]
OK, I missed this information.

S/2003 J 24 was annouced novembre 15th 2021
https://www.minorplanetcenter.net/mpec/K21/K21VX3.html

I will add it in some days.

**Comment by khrys63** [comment]
added ^^
