### ISSUE TITLE
Some Sideral Orbit inconsistencies I noticed

### ISSUE THREAD

**Issue by Jollus174** [systeme-solaire/api-rest#12]
Chariklo sideralOrbit listed as 23, should be 22987.
https://api.le-systeme-solaire.net/rest/bodies/chariklo

Cleoselene should be 1.8 (according to Wikipedia).
https://api.le-systeme-solaire.net/rest/bodies/cleoselene

Weywot to be 12.438.
https://api.le-systeme-solaire.net/rest/bodies/weywot

**Comment by khrys63** [comment]
I fixed those data and for 17 other body.
I find 40 other with bad data.

I'll fix it soon

**Comment by khrys63** [comment]
I Fixed all other data.
