### ISSUE TITLE
Asc and desc use (may be a bug)

### ISSUE THREAD

**Issue by lazcanoluca** [systeme-solaire/api-rest#13]
Hi!

I'm making the following request:

https://api.le-systeme-solaire.net/rest/bodies/?data=id,meanRadius&order=meanRadius,desc&filter[]=isPlanet,eq,-1

expecting to see the planets listed in decreasing meanRadius order. However, they appear listed in increasing meanRadius order.

I've tried using different keywords instead of "desc" but none appears to be working.

Please, let me know if I'm doing something wrong, or it's a bug to be fixed.

Great job, thank you!

**Comment by khrys63** [comment]
It's a bug and it's fixed
Thanks for feedback.
