### ISSUE TITLE
Some field-related issues I spotted

### ISSUE THREAD

**Issue by Jollus174** [systeme-solaire/api-rest#16]
NEOWISE is missing an englishName. Should be **C/2020 F3 (NEOWISE)"**
https://api.le-systeme-solaire.net/rest/bodies/c2020f3-neowise

_Junon_'s englishName should be **3 Juno**.
https://api.le-systeme-solaire.net/rest/bodies/junon

Venus, Uranus and Pluto have negative numbers as their `sideralRotation`, but I'm unsure if this is intentional.
https://api.le-systeme-solaire.net/rest/bodies/venus
https://api.le-systeme-solaire.net/rest/bodies/uranus
https://api.le-systeme-solaire.net/rest/bodies/pluton

**Comment by khrys63** [comment]
I fixed data for neowise and 3 Juno.

**Comment by khrys63** [comment]
sideralRotation is negative on those objects because Venus, Uranus aned Pluto are retrograde.
