### ISSUE TITLE
Quaoar listed as 'Asteroid'

### ISSUE THREAD

**Issue by Jollus174** [systeme-solaire/api-rest#18]
It should be **Dwarf Planet**.
https://api.le-systeme-solaire.net/rest/bodies/quaoar

**Comment by khrys63** [comment]
No, Quaoar is not a dwarf planet.
In the official def by IAU, only Pluton, Haumea, Ceres, Eris and Makemake are Dwarf Planet. 
It's not the blog of Mickael E Brown here :)

**Comment by Jollus174** [comment]
Ahh, my mistake sorry.

Initially it looked like sources were saying it was, but after looking around it looks like it's still under consideration.
