### ISSUE TITLE
englishName fields for Saturn's moons seem to have gone missing

### ISSUE THREAD

**Issue by Jollus174** [systeme-solaire/api-rest#19]
![image](https://user-images.githubusercontent.com/30223207/150148594-8378c5bd-fb9d-497c-a61c-4b1b5fec22e7.png)
https://api.le-systeme-solaire.net/rest/bodies/
Looks like the englishNames went missing recently for:
- S/2004 S 22
- S/2004 S 21
- S/2004 S 20
- S/2004 S 23
- S/2004 S 24
- S/2004 S 25
- S/2004 S 26
- S/2004 S 27
- S/2004 S 28
- S/2004 S 29
- S/2004 S 30
- S/2004 S 31
- S/2004 S 32
- S/2004 S 33
- S/2004 S 34
- S/2004 S 35
- S/2004 S 36
- S/2004 S 37
- S/2004 S 38
- S/2004 S 39

Also one for Jupiter:
- S/2003 J 24

**Comment by khrys63** [comment]
hi, I fixed it
Thx for feedback.
