### ISSUE TITLE
Discovery Data for some planets don't exist. 

### ISSUE THREAD

**Issue by DanCRichards** [systeme-solaire/api-rest#2]
Discovered By / Discovery Date data doesn't exist for some of the major 9 planets in our solar system.

**Comment by Guerau1714** [comment]
discoveredBy & discoveryDate are missing for some planets (Mercury, Venus, Earth, Mars, Jupiter & Saturn) because they have been known for thousands of years. So we don't know who discovered them or when.

**Comment by khrys63** [comment]
Discovered Date is present for
- Ceres
- Eris
- Uranus
- Neptune
- Pluto
- Haumea
- Makemake
For all other planet, the date doesn't exists.
