### ISSUE TITLE
Using the filter isPlanet,eq,true

### ISSUE THREAD

**Issue by Zhorian** [systeme-solaire/api-rest#3]
I expect using the above filter would give me back just the records where isPlanet is true however it's bringing back only the records where is planet is false.

https://api.le-systeme-solaire.net/rest/bodies?data=id,englishName,isPlanet&filter[]=isPlanet,eq,true&order=englishName,asc

**Comment by kmassicotte** [comment]
I noticed this bug too when testing the API via Swagger. To work around, use the negative: `isPlanet,neq,false`

**Comment by AntoineGGG** [comment]
Yup, same here, you can use `isPlanet,neq,true` too.

**Comment by khrys63** [comment]
hi, 
for boolean, we must use -1 for true and 0 for false.
https://api.le-systeme-solaire.net/rest.php/bodies?filter[]=isPlanet,eq,-1

I will fix it as soon as possible

**Comment by khrys63** [comment]
It's OK
thanks for feedback
