### ISSUE TITLE
Average Temperature is 0 for all bodies.

### ISSUE THREAD

**Issue by ad9311** [systeme-solaire/api-rest#8]
The average temperature for all bodies is 0. `{..., avgTemp: 0}`

**Comment by khrys63** [comment]
hi thanks for feedback.

Actually, average temperature is present just for planets and dwarf planets.

**Comment by danielriverolosa** [comment]
Hello,
I'm testing the api and it returns avgTemp 0 for planets as well.

**Comment by khrys63** [comment]
it's OK now.
