### ISSUE TITLE
Dwarf Planets are considered planets ("isPlanet":true) when they're not

### ISSUE THREAD

**Issue by Guerau1714** [systeme-solaire/api-rest#9]
The Dwarf planets: Ceres, Eris, Pluto, Makemake & Haumea are considered as planets in `"isPlanet":true`. This should be changed to false, as they're not actually planets.  The [IAU](https://www.iau.org/public/themes/pluto/) doesn't consider Pluto (and other dwarf planets) as planets.

**Comment by Jollus174** [comment]
I concur with these. It'd be handy if instead of an `isPlanet` boolean, we could instead use something like a type string instead.
Then each item could contain one of the following:
```
type: 'Star'
type: 'Planet'
type: 'Moon'
type: 'Dwarf Planet'
type: 'Asteroid'
```

**Comment by khrys63** [comment]
I added bodyType with 'Star', 'Planet', 'Moon', 'Dwarf Planet', 'Asteroid' and 'Comet' Value

Coding filter soon

**Comment by khrys63** [comment]
Added Filter bodyType.

Thanks all for feedback
